# Generated by Django 3.0.4 on 2020-04-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
