# Generated by Django 3.0.4 on 2020-04-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_questionnaire_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='communicationValue',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='contractConditionsValue',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='currentSituationValue',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='expectationsValue',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='futureParthershipValue',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='placementValue',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='politenessValue',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='qualityValue',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='recommendationValue',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='safetyValue',
        ),
    ]
