# Generated by Django 3.0.4 on 2020-04-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200423_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='user_pk',
            new_name='renter_pk',
        ),
        migrations.AlterField(
            model_name='survey',
            name='review',
            field=models.TextField(default='Пустой отзыв', max_length=5000),
        ),
    ]
