# Generated by Django 3.0.4 on 2020-04-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200423_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='landlord_pk',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='renter_pk',
        ),
        migrations.AddField(
            model_name='survey',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
